/*
 * data_model_snapshot.c
 * 
 * Snapshot of code generation data model.
 * This information is included in the executable file
 * and does not affect any memory content in the embedded device.
 */
 
__attribute__((section("diagnostics_cinfo, info"), keep)) char MCAF_data_model_snapshot[] =
  "{\"motor\": {\"Tfr\": 0.0143238350133,\"B\": 3.9961462067e-05,\"Lq\": 0.00035,\""
  "poleCount\": 8,\"rated_current\": 2.0,\"J\": 0.000284285514219,\"velocity\": {\""
  "nominal\": 282.743338823,\"maximum\": 314.159265359,\"units\": \"rad\\/s\"},\"L"
  "\": 0.000325,\"R\": 0.5,\"current\": {\"maximum\": {\"continuous\": 2.0,\"peak\""
  ": 3.0},\"units\": \"A\"},\"Ld\": 0.0003,\"Ke\": 0.0372743524276,\"id\": \"Rika F"
  "an\"},\"controller\": {\"encoder\": {\"tracking_loop\": {\"zeta\": 1.5}},\"foc\""
  ": {\"feedback\": {\"voltage_delay\": 0}},\"pll\": {\"delay_match\": true,\"prope"
  "rties\": {\"reference\": false},\"keInverseScaling\": 1.0},\"operation\": {\"min"
  "_deceleration_time\": null},\"dyn_current\": {\"maxgain\": 1.1},\"zsmt\": {\"err"
  "orLimit\": 0.99997,\"properties\": {\"independent\": true,\"reference\": false},"
  "\"duration\": {\"lockDelay\": 0.05},\"probe\": {\"accumGain\": 1.0}},\"fault_det"
  "ect\": {\"recovery\": {\"attempts\": 3}}},\"metadata\": {\"MCC\": {\"architectur"
  "e\": \"melody\",\"peripherals\": {\"instances\": [{\"name\": \"ADC1\",\"type\": "
  "\"adc\"},{\"name\": \"PWM\",\"type\": \"pwm_hs\"},{\"name\": \"QEI1\",\"type\": "
  "\"qei\"},{\"name\": \"TMR1\",\"type\": \"timer\"},{\"name\": \"SCCP1\",\"type\":"
  " \"timer\"},{\"name\": \"UART1\",\"type\": \"uart\"},{\"name\": \"OPA1\",\"type"
  "\": \"opa\"},{\"name\": \"OPA2\",\"type\": \"opa\"},{\"name\": \"OPA3\",\"type\""
  ": \"opa\"}]},\"version\": \"5.7.1\",\"peripheral_library\": {\"name\": \"melody"
  "\",\"version\": \"NA\"}},\"data_model\": {\"schema_version\": 5},\"motorBench\":"
  " {\"commit_id\": \"6062ee969f17e173cb8502638f1e3c8ee7bea3fb\",\"version\": \"2.4"
  "5.0\"},\"MCAF\": {\"build\": {\"commit_id\": \"116330\",\"date_str\": \"2023 Feb"
  " 09\",\"hostname\": \"motor-control-mcaf-tags-builder-r7-2frc37-1-0ws3m-smcgr-kt"
  "hrw\",\"time\": 1675959683.33,\"time_iso\": \"2023-02-09T16:21:23.327489\",\"tim"
  "e_str\": \"2023 Feb 09 16:21\",\"type\": \"release\",\"username\": \"jenkins\","
  "\"version\": \"R7\\/RC37\"},\"build_time\": 1675959683.33,\"build_time_iso\": \""
  "2023-02-09T16:21:23.327489\",\"build_time_str\": \"2023 Feb 09 16:21\",\"commit_"
  "id\": \"116330\",\"version\": \"R7\\/RC37\"}},\"scdata\": {\"setup\": {\"communi"
  "cations\": {\"baudrate\": 625000},\"analysis\": {\"spindown_time\": {\"units\": "
  "\"s\",\"value\": 1.0},\"max_motor_speed\": {\"units\": \"rad\\/s mechanical\",\""
  "value\": 2094.4}},\"calibration\": {\"vdc\": {\"units\": \"V\",\"value\": 24.0},"
  "\"resistor\": {\"units\": \"ohms\",\"value\": 12.0}}}},\"autotune_result\": {\"c"
  "urrent\": {\"Kp\": 0.546677471309,\"phase_margin\": 80.0,\"wc\": 1826.71942231,"
  "\"Ki\": 998.626354579,\"pi_phase_lag\": 45.0},\"velocity\": {\"Kp\": 0.404683320"
  "203,\"phase_margin\": 65.0,\"wc\": 79.3598191843,\"Ki\": 5.66284592085,\"pi_phas"
  "e_lag\": 10.0}},\"code_generation_tag_map\": {\"application\": \"sample\",\"diag"
  "nostics\": \"x2cscope\"},\"operating_range\": {\"velocity\": {\"units_qualifier"
  "\": \"mechanical\",\"units\": \"rad\\/s\",\"minimum\": 130.89975}},\"build\": {"
  "\"hardware_spec\": \"mclv2:33ck256mp508_extopamp_pim\",\"normfactor_associations"
  "\": [{\"context\": null,\"annotations\": [{\"typerefs\": [\"MCAF_U_CURRENT_ABC\""
  ",\"MCAF_U_CURRENT_ALPHABETA\",\"MCAF_U_CURRENT_DQ\",\"MCAF_U_CURRENT\",\"MCAF_MO"
  "TOR_DATA.omegaCtrl.outMin\",\"MCAF_MOTOR_DATA.omegaCtrl.outMax\"],\"unit\": \"I"
  "\",\"q\": 15},{\"typerefs\": [\"MCAF_MOTOR_DATA.omegaCtrl.integrator\"],\"unit\""
  ": \"I\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VOLTAGE_ABC\",\"MCAF_U_VOLTAGE_ALPHA"
  "BETA\",\"MCAF_U_VOLTAGE_DQ\",\"MCAF_U_VOLTAGE\",\"MCAF_MOTOR_DATA.idCtrl.outMin"
  "\",\"MCAF_MOTOR_DATA.idCtrl.outMax\",\"MCAF_MOTOR_DATA.iqCtrl.outMin\",\"MCAF_MO"
  "TOR_DATA.iqCtrl.outMax\"],\"unit\": \"V\",\"q\": 15},{\"typerefs\": [\"MCAF_MOTO"
  "R_DATA.idCtrl.integrator\",\"MCAF_MOTOR_DATA.iqCtrl.integrator\"],\"unit\": \"V"
  "\",\"q\": 31},{\"typerefs\": [\"MCAF_U_DUTYCYCLE_ABC\"],\"unit\": 1,\"q\": 15},{"
  "\"typerefs\": [\"MCAF_U_ANGLE_ELEC\"],\"unit\": \"theta_e\",\"q\": 15},{\"typere"
  "fs\": [\"MCAF_U_ANGLE_MECH\"],\"unit\": \"theta_m\",\"q\": 15},{\"typerefs\": ["
  "\"MCAF_U_VELOCITY_MECH\"],\"unit\": \"omega_m\",\"q\": 15},{\"typerefs\": [\"MCA"
  "F_U_VELOCITY_ELEC\"],\"unit\": \"omega_e\",\"q\": 15},{\"typerefs\": [\"MCAF_U_V"
  "ELOCITY_DTHETA_ELEC_DT\"],\"unit\": \"dtheta_elec_dt\",\"q\": 15},{\"typerefs\":"
  " [\"MCAF_U_TEMPERATURE\"],\"unit\": \"Temperature\",\"q\": 15},{\"typerefs\": ["
  "\"MCAF_U_DIMENSIONLESS\",\"MCAF_U_DIMENSIONLESS_SINCOS\"],\"unit\": 1,\"q\": 15}"
  ",{\"typerefs\": [\"MCAF_U_NORMALIZED_GAIN\"],\"unit\": 1,\"q\": 14}]}]},\"drive"
  "\": {\"iout\": {\"measurement\": {\"compensation\": {\"channels\": [\"a\",\"b\"]"
  ",\"values\": {\"a\": [1.0,0.0],\"b\": [0.0,1.0]},\"offset\": {\"range\": 0.03125"
  ",\"samples\": 128,\"filterGain\": 0.25}}},\"time_constant\": 5.971e-07,\"fullsca"
  "le\": 22.044,\"maximum\": {\"continuous\": 16.79},\"units\": \"A\"},\"estimator"
  "\": {\"type\": \"pll\",\"runtimeSelect\": false,\"atpll\": {\"tau1\": 0.0001,\"t"
  "au2\": 0.00219,\"kpfactor\": 1.9,\"kifactor\": 30},\"omega1\": 732.0,\"tau\": 0."
  "00219},\"flux_control\": {\"emag_tau\": 0.001638,\"idref_tau\": 0.006552},\"temp"
  "erature\": {\"fullscale\": 327.68,\"units\": \"C\"},\"pwm\": {\"adc_sampling_del"
  "ay\": 0,\"period\": 5e-05,\"duty_cycle\": {\"maximum\": 0.945,\"minimum\": 0.014"
  "},\"deadtime\": 5.9e-07},\"mcaf\": {\"adc\": {\"triggerSettings\": {\"noTrigger"
  "\": \"NO_TRIGGER\",\"trigger1\": \"PWM1_TRIGGER1\",\"trigger2\": \"PWM1_TRIGGER2"
  "\"},\"channels\": {\"prefix\": \"MCAF_ADC_\",\"critical\": [\"PHASEA_CURRENT\","
  "\"PHASEB_CURRENT\",\"PHASEC_CURRENT\",\"DCLINK_CURRENT\",\"DCLINK_VOLTAGE\"],\"r"
  "equired\": {\"single_channel\": [\"DCLINK_CURRENT\",\"DCLINK_VOLTAGE\",\"POTENTI"
  "OMETER\"],\"dual_channel\": [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\",\"DCLINK_VOLT"
  "AGE\",\"POTENTIOMETER\"],\"triple_channel\": [\"PHASEA_CURRENT\",\"PHASEB_CURREN"
  "T\",\"PHASEC_CURRENT\",\"DCLINK_VOLTAGE\",\"POTENTIOMETER\"]},\"optional\": [\"P"
  "HASEA_VOLTAGE\",\"PHASEB_VOLTAGE\",\"PHASEC_VOLTAGE\",\"BRIDGE_TEMPERATURE\",\"A"
  "BSREF_VOLTAGE\"],\"fullList\": [{\"name\": \"PHASEA_CURRENT\",\"c_fragment\": \""
  "IphaseA\",\"description\": \"phase A current\"},{\"name\": \"PHASEB_CURRENT\",\""
  "c_fragment\": \"IphaseB\",\"description\": \"phase B current\"},{\"name\": \"PHA"
  "SEC_CURRENT\",\"c_fragment\": \"IphaseC\",\"description\": \"phase C current\"},"
  "{\"name\": \"PHASEA_VOLTAGE\",\"c_fragment\": \"VphaseA\",\"description\": \"pha"
  "se A voltage\"},{\"name\": \"PHASEB_VOLTAGE\",\"c_fragment\": \"VphaseB\",\"desc"
  "ription\": \"phase B voltage\"},{\"name\": \"PHASEC_VOLTAGE\",\"c_fragment\": \""
  "VphaseC\",\"description\": \"phase C voltage\"},{\"name\": \"DCLINK_CURRENT\",\""
  "c_fragment\": \"Ibus\",\"description\": \"DC link current\"},{\"name\": \"DCLINK"
  "_VOLTAGE\",\"c_fragment\": \"Dclink\",\"description\": \"DC link voltage\"},{\"n"
  "ame\": \"POTENTIOMETER\",\"c_fragment\": \"Potentiometer\",\"description\": \"po"
  "tentiometer voltage\"},{\"name\": \"BRIDGE_TEMPERATURE\",\"c_fragment\": \"Bridg"
  "eTemperature\",\"description\": \"bridge temperature voltage\"},{\"name\": \"ABS"
  "REF_VOLTAGE\",\"c_fragment\": \"AbsoluteReferenceVoltage\",\"description\": \"ab"
  "solute reference voltage\"}]}}},\"metadata\": {\"name\": \"MCLV-48V-300W Develop"
  "ment Board\",\"id\": \"mclv-48v-300w\"},\"vdc\": {\"nominal\": 24.0,\"time_const"
  "ant\": 2.87e-05,\"fullscale\": 75.9,\"maximum\": 48.0,\"units\": \"V\",\"minimum"
  "\": 12.0},\"configuration\": {\"metadata\": {\"capability\": {\"adc\": {\"channe"
  "l\": {\"ABSREF_VOLTAGE\": \"AN6\",\"PHASEB_VOLTAGE\": \"AN11\",\"PHASEB_CURRENT"
  "\": \"AN4\",\"PHASEA_VOLTAGE\": \"AN10\",\"PHASEC_CURRENT\": \"AN16\",\"POTENTIO"
  "METER\": \"AN17\",\"BRIDGE_TEMPERATURE\": \"AN18\",\"DCLINK_VOLTAGE\": \"AN15\","
  "\"PHASEA_CURRENT\": \"AN1\",\"PHASEC_VOLTAGE\": \"AN12\",\"DCLINK_CURRENT\": \"A"
  "N0\"}},\"opamp\": \"internal\",\"buttonCount\": 2.0,\"current_measure\": {\"a\":"
  " true,\"b\": true,\"c\": true,\"dc\": true}},\"scaling\": {\"temperature\": {\"b"
  "ridge\": {\"offset\": 5000.0,\"gain\": 0.50354}}},\"peripherals\": {\"adc\": {\""
  "core\": {\"names\": [\"Core0\",\"Core1\",\"SharedCore\"]}}},\"pim\": {\"algorith"
  "m\": {\"single_channel\": {\"supported\": true}},\"device\": \"33ck256mp508\",\""
  "displayName\": \"dsPIC33CK256MP508\",\"id\": \"33ck256mp508_dim\",\"opamp\": \"i"
  "nternal\",\"peripherals\": {\"adc\": {\"core\": {\"names\": [\"Core0\",\"Core1\""
  ",\"SharedCore\"]}}}},\"device\": \"33ck256mp508\",\"board\": {\"id\": \"mclv-48v"
  "-300w\"}},\"peripherals\": {\"adc\": {\"requestedDedCoreSamplingTimeData\": [{\""
  "core\": \"Core0\",\"requestedSamplingTime_us\": 0.3},{\"core\": \"Core1\",\"requ"
  "estedSamplingTime_us\": 0.3}],\"dataOutputFormat\": \"Fractional\",\"channelConf"
  "ig\": [{\"channel\": \"AN1\",\"sign\": \"signed\",\"core\": \"Core1\",\"customNa"
  "me\": \"MCAF_ADC_PHASEA_CURRENT\",\"inverted\": true},{\"channel\": \"AN4\",\"si"
  "gn\": \"signed\",\"core\": \"Shared\",\"customName\": \"MCAF_ADC_PHASEB_CURRENT"
  "\",\"inverted\": true},{\"channel\": \"AN16\",\"sign\": \"signed\",\"core\": \"S"
  "hared\",\"customName\": \"MCAF_ADC_PHASEC_CURRENT\",\"inverted\": true},{\"chann"
  "el\": \"AN0\",\"sign\": \"signed\",\"core\": \"Core0\",\"customName\": \"MCAF_AD"
  "C_DCLINK_CURRENT\",\"inverted\": false},{\"channel\": \"AN15\",\"sign\": \"signe"
  "d\",\"core\": \"Shared\",\"customName\": \"MCAF_ADC_DCLINK_VOLTAGE\"},{\"channel"
  "\": \"AN6\",\"sign\": \"unsigned\",\"core\": \"Shared\",\"customName\": \"MCAF_A"
  "DC_ABSREF_VOLTAGE\"},{\"channel\": \"AN17\",\"sign\": \"signed\",\"core\": \"Sha"
  "red\",\"customName\": \"MCAF_ADC_POTENTIOMETER\"},{\"channel\": \"AN18\",\"sign"
  "\": \"unsigned\",\"core\": \"Shared\",\"customName\": \"MCAF_ADC_BRIDGE_TEMPERAT"
  "URE\"},{\"channel\": \"AN10\",\"sign\": \"unsigned\",\"core\": \"Shared\",\"cust"
  "omName\": \"MCAF_ADC_PHASEA_VOLTAGE\"},{\"channel\": \"AN11\",\"sign\": \"unsign"
  "ed\",\"core\": \"Shared\",\"customName\": \"MCAF_ADC_PHASEB_VOLTAGE\"},{\"channe"
  "l\": \"AN12\",\"sign\": \"unsigned\",\"core\": \"Shared\",\"customName\": \"MCAF"
  "_ADC_PHASEC_VOLTAGE\"}],\"customName\": \"MCC_ADC\",\"interruptDriven\": false,"
  "\"requestedSharedSamplingTime_us\": 0.3,\"resolution\": 12.0},\"timer\": [{\"req"
  "uestedTimerPeriod_ms\": 1.0,\"customName\": \"MCC_TMR_TICK\",\"interruptDriven\""
  ": true},{\"clkSrc\": \"FCY\",\"customName\": \"MCC_TMR_PROFILE\",\"interruptDriv"
  "en\": false,\"clkPrescaler\": 1.0,\"periodCount\": 65535.0}],\"oscillator\": {\""
  "clockSource\": \"External Oscillator with PLL\",\"requestedSystemFrequency_Hz\":"
  " 0.0,\"defaultValue\": \"max-frequency\",\"setMaximumSystemFrequency\": true,\"c"
  "lockSourceFrequency\": 8000000.0},\"opamp\": [{\"customName\": \"MCC_OPA_IDC\","
  "\"enable\": true,\"instance\": 1.0},{\"customName\": \"MCC_OPA_IA\",\"enable\": "
  "true,\"instance\": 2.0},{\"customName\": \"MCC_OPA_IB\",\"enable\": true,\"insta"
  "nce\": 3.0}],\"qei\": [{\"noiseFilterEnable\": false,\"pinMapping\": [{\"pin\": "
  "\"RC4\",\"functionName\": \"A\",\"direction\": \"input\"},{\"pin\": \"RC5\",\"fu"
  "nctionName\": \"B\",\"direction\": \"input\"},{\"pin\": \"RD2\",\"functionName\""
  ": \"INDX\",\"direction\": \"input\"}],\"qeiOperationMode\": \"Modulo Count mode"
  "\",\"indexPulseCaptureEnable\": false,\"homePulseCaptureEnable\": false,\"homePu"
  "lsePolarity\": false,\"customName\": \"MCC_QEI\",\"indexPulsePolarity\": false}]"
  ",\"wdt\": {\"wdtEnable\": true,\"requestedWdtPeriod_ms\": 1.0,\"wdtMode\": \"Non"
  "-Window mode\",\"wdtEnableType\": \"Software\"},\"pwm\": {\"synchronousUpdate\":"
  " true,\"duty_cycle\": {\"maximum\": 0.945,\"minimum\": 0.014},\"requestedDeadTim"
  "e_us\": {\"defaultValue\": 0.59,\"maximum\": 6.0,\"minimum\": 0.385},\"customNam"
  "e\": \"MCC_PWM\",\"generatorMapping\": [{\"name\": \"MOTOR1_PHASE_A\",\"generato"
  "r\": 1.0},{\"name\": \"MOTOR1_PHASE_B\",\"generator\": 2.0},{\"name\": \"MOTOR1_"
  "PHASE_C\",\"generator\": 3.0}],\"interruptDriven\": false,\"faultInputPolarity\""
  ": \"Active-low\",\"frequency\": {\"defaultValue\": 20000.0,\"maximum\": 50000.0,"
  "\"minimum\": 1000.0},\"faultInputSource\": \"Device pin, PCI20\",\"polarity\": {"
  "\"lower\": \"Active-high\",\"upper\": \"Active-high\"}},\"uart\": {\"baudRate\":"
  " 115200.0,\"pinMapping\": [{\"name\": \"TX\",\"pinSelected\": \"RD14\"},{\"name"
  "\": \"RX\",\"pinSelected\": \"RD13\"}],\"stopBits\": 1.0,\"parity\": \"None\",\""
  "dataSize\": 8.0,\"customName\": \"MCC_UART\",\"interruptDriven\": false},\"gpio"
  "\": [{\"isWeakPullUp\": false,\"pinSelected\": \"RE12\",\"interruptOnChange\": "
  "\"none\",\"isWeakPullDown\": false,\"customName\": \"MCAF_LED1\",\"isAnalogPin\""
  ": false,\"direction\": \"output\",\"isOpenDrain\": false},{\"isWeakPullUp\": fal"
  "se,\"pinSelected\": \"RE13\",\"interruptOnChange\": \"none\",\"isWeakPullDown\":"
  " false,\"customName\": \"MCAF_LED2\",\"isAnalogPin\": false,\"direction\": \"out"
  "put\",\"isOpenDrain\": false},{\"isWeakPullUp\": false,\"pinSelected\": \"RE10\""
  ",\"interruptOnChange\": \"none\",\"isWeakPullDown\": false,\"customName\": \"MCA"
  "F_BUTTON1\",\"isAnalogPin\": false,\"direction\": \"input\",\"isOpenDrain\": fal"
  "se},{\"isWeakPullUp\": false,\"pinSelected\": \"RE11\",\"interruptOnChange\": \""
  "none\",\"isWeakPullDown\": false,\"customName\": \"MCAF_BUTTON2\",\"isAnalogPin"
  "\": false,\"direction\": \"input\",\"isOpenDrain\": false},{\"isWeakPullUp\": fa"
  "lse,\"pinSelected\": \"RE8\",\"interruptOnChange\": \"none\",\"isWeakPullDown\":"
  " false,\"customName\": \"MCAF_TESTPOINT1\",\"isAnalogPin\": false,\"direction\":"
  " \"output\",\"isOpenDrain\": false}]},\"displayName\": \"MCLV-48V-300W\",\"name"
  "\": \"MCLV-48V-300W Inverter Board\",\"partNumber\": \"EV18H47A\",\"id\": \"mclv"
  "-48v-300w\",\"supportedPim\": [\"33ck256mp508_dim\",\"33ck64mc105_dim\"]},\"idc"
  "\": {\"maximum\": 2.9,\"units\": \"A\"},\"sampling_time\": {\"current\": 5e-05,"
  "\"velocity\": 0.001},\"processor\": {\"clock_frequency\": 100000000.0,\"pim\": "
  "\"dsPIC33CK256MP508\",\"familyName\": \"dsPIC33CK256MP508\",\"device\": \"dsPIC3"
  "3CK256MP508\"},\"vbus\": 24.0},\"config\": {\"ui\": {\"content\": {\"current_mea"
  "sure-method\": \"dual_channel\",\"current_measure-single_channel-minimumTime\": "
  "2.0,\"current_measure-single_channel-sampleDelay\": 0.0,\"current_measure-opamp-"
  "full_input_range\": true,\"estimator-type\": \"pll\",\"estimator-active-pll\": f"
  "alse,\"estimator-active-qei\": false,\"estimator-active-atpll\": false,\"estimat"
  "or-active-zsmt\": false,\"estimator-active-ideal\": false,\"operation-min_veloci"
  "ty_ratio\": 0.25,\"operation-startup_velocity_ratio\": 0.2744,\"operation-max_ve"
  "locity_ratio\": 1.25,\"operation-fullscale_base_ratio\": 1.5,\"operation-outer_l"
  "oop_type\": \"velocity\",\"operation-saliency-threshold\": 1.25,\"operation-slew"
  "rate-accel\": 0.5,\"operation-slewrate-decel\": 1.0,\"operation-dyn_current_type"
  "\": \"none\",\"operation-stopping-type\": \"minimal_impact\",\"operation-stoppin"
  "g-closed_loop_parameters-speed\": 0.05,\"operation-stopping-closed_loop_paramete"
  "rs-time\": 0.5,\"operation-coastdown-end_velocity\": 0.05,\"operation-coastdown-"
  "time\": 1.2,\"fault_inject-get_tf-div0\": false,\"fault_inject-get_tf-missing_da"
  "ta\": false,\"fault_inject-get_tf-raise_value_error\": false,\"fault_inject-get_"
  "tf-raise_custom_error\": false,\"fault_inject-tf-tf_null\": false,\"fault_inject"
  "-tf-tf_jy\": false,\"fault_inject-tf-tf_jyex\": false,\"fault_inject-tf-div0\": "
  "false,\"fault_inject-tf-tau\": 0.0,\"flux_control-method\": \"none\",\"flux_cont"
  "rol-eqn_based-ilimit-region_type\": \"quadratic\",\"flux_control-eqn_based-ilimi"
  "t-id_limit\": 0.7,\"flux_control-eqn_based-ilimit-iq_limit\": 0.95,\"flux_contro"
  "l-eqn_based-fluxweak_enable\": false,\"flux_control-eqn_based-fw-vdq_limit\": 0."
  "95,\"flux_control-eqn_based-mtpa_enable\": false,\"deadtimecomp-method\": \"none"
  "\",\"deadtimecomp-perphase-current_sign_band\": 0.02,\"deadtimecomp-perphase-for"
  "ward_gain\": 0.0,\"deadtimecomp-perphase-feedback_gain\": 0.0,\"fault_detect-mar"
  "gin_uv\": 2.0,\"fault_detect-margin_ov\": 2.0,\"fault_detect-stall_detect_enable"
  "\": true,\"startup-Istartup\": 0.75,\"startup-t_rampup\": 25.0,\"startup-t_align"
  "\": 0.0,\"startup-min_total_accel_time\": 250.0,\"startup-torque_scale_accel\": "
  "0.15,\"startup-torque_scale_slow_accel\": 0.2,\"startup-t_hold\": 0.0,\"startup-"
  "omega0\": 0.2,\"startup-theta_converge_rate\": 1.0,\"startup-method\": \"classic"
  "\",\"startup-damping-Imax\": 0.1,\"startup-damping-gainmax\": 40.0,\"startup-dam"
  "ping-omega_min\": 0.4,\"overmodulation-vd_limit\": 1.0,\"overmodulation-vq_limit"
  "\": 1.15,\"overmodulation-include_duty_clipping\": true,\"pll-tau\": 2.19,\"pll-"
  "omega1\": 116.5,\"pll-velocity_filter_threshold\": 1.0,\"encoder-lines\": 250.0,"
  "\"encoder-index_present\": false,\"encoder-tracking_loop-tau\": 1.5,\"encoder-qe"
  "i_sync-method\": \"align\",\"encoder-qei_sync-align-t_align\": 0.5,\"encoder-qei"
  "_sync-align-angle_shift\": 30.0,\"encoder-qei_sync-align-angle_init\": -30.0,\"e"
  "ncoder-qei_sync-align_sweep-sweep_rate_pow\": 1.0,\"encoder-qei_sync-align_sweep"
  "-setup_angle\": 45.0,\"encoder-qei_sync-pullout-pullout_slip\": 0.117,\"zsmt-exc"
  "itation-kV\": 0.12,\"zsmt-excitation-kI\": 0.1,\"zsmt-pll-zeta\": 1.5,\"zsmt-pll"
  "-tau\": 10.0,\"zsmt-pll-tau_lpf\": 0.0,\"zsmt-pll-execution_divider\": 2.0,\"zsm"
  "t-startup-align_delay\": 1.0,\"zsmt-startup-pll_lock_time\": 1.0,\"zsmt-startup-"
  "speed_limit\": 0.015,\"zsmt-startup-current_limit\": 0.3,\"zsmt-startup-probe_du"
  "ration\": 10.0,\"zsmt-startup-probe_slew_time\": 1.5,\"zsmt-startup-probe_blanki"
  "ng_time\": 4.0,\"zsmt-hybrid-type\": \"minotaur\",\"zsmt-minotaur-voltage_limit-"
  "vd\": 0.45,\"zsmt-minotaur-voltage_limit-vq\": 0.78,\"zsmt-minotaur-converge-ang"
  "le\": 10.0,\"zsmt-minotaur-converge-duration\": 2.0,\"zsmt-minotaur-velocity_thr"
  "eshold-slow\": 0.15,\"zsmt-minotaur-velocity_threshold-transition\": 0.2,\"zsmt-"
  "minotaur-velocity_threshold-fast\": 0.25,\"zsmt-angle_correction-current_gain\":"
  " 0.0,\"dyn_current1-peak_factor\": 1.0,\"dyn_current1-horizon_factor\": 1.05,\"d"
  "yn_current1-tau\": 5.0,\"dyn_current1-nsamples\": 128.0,\"voltage_outerloop-tau_"
  "lpf\": 2.0,\"voltage_outerloop-Kp\": 0.1,\"voltage_outerloop-tau\": 100.0,\"mcap"
  "i-isSquaredTau\": 1.0,\"mcapi-iqTau\": 1.0,\"mcapi-adcIsrUserFunctions_enable\":"
  " false,\"board_service-uiServiceTiming\": 1.0,\"board_service-uiButtonDebounceTi"
  "me\": 7.0,\"board_service-uiButtonLongPressTime\": 2.5,\"test_harness-perturbati"
  "on_asymmetric\": false,\"adc-vtempbridge\": false,\"adc-temp_bridge_params-thres"
  "hold\": 50.0,\"adc-temp_bridge_params-tau_lpf\": 10.0,\"adc-temp_bridge_params-s"
  "lewrate\": 4.0,\"adc-vabsref\": false,\"adc-vphasea\": false,\"adc-vphaseb\": fa"
  "lse,\"adc-vphasec\": false},\"version\": {\"schema\": 4.0,\"motorBench\": \"2.45"
  ".0\",\"MCAF\": \"R7\"},\"status\": {\"valid\": true}}}}";